# Generated by Django 4.0.4 on 2022-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeTitle', models.CharField(max_length=250)),
                ('noticeFile', models.FileField(upload_to='noticeboard')),
                ('noticeTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
