# Generated by Django 4.0.4 on 2022-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderTitle', models.CharField(max_length=250)),
                ('tenderFile', models.FileField(upload_to='tender')),
                ('tenderTime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='noticeTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
