# Generated by Django 4.0.4 on 2022-05-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0002_tender_alter_noticeboard_noticetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=250)),
                ('eventDate', models.FileField(upload_to='tender')),
                ('galleryThumbnail', models.FileField(upload_to='gallery')),
                ('galleryLink', models.DateField(auto_now=True)),
            ],
        ),
    ]
