# Generated by Django 4.0.4 on 2022-05-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0003_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='galleryLink',
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallerUrl',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='eventDate',
            field=models.DateField(auto_now=True),
        ),
    ]
