# Generated by Django 4.0.4 on 2022-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0005_post_postarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocationTitle', models.CharField(max_length=250)),
                ('convocationDate', models.DateField(auto_now=True)),
                ('convocationgallerUrl', models.URLField(max_length=500, null=True)),
                ('convocationgalleryThumbnail', models.FileField(upload_to='convocation')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostArchive',
        ),
    ]
