# Generated by Django 4.0.4 on 2022-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0006_convocation_delete_post_delete_postarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=250)),
                ('facultyDesignation', models.CharField(max_length=250)),
                ('facultyQualification', models.CharField(max_length=250)),
                ('facultyPhone', models.CharField(max_length=250)),
                ('facultyEmail', models.EmailField(max_length=250)),
                ('facultyCv', models.FileField(upload_to='facultycv')),
                ('facultyPublications', models.URLField(max_length=250, null=True)),
            ],
        ),
    ]
