# Generated by Django 4.0.4 on 2022-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0007_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facultyImage',
            field=models.ImageField(null=True, upload_to='facultyimg'),
        ),
    ]
