# Generated by Django 4.0.4 on 2022-05-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0009_upcominglectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeorderTitle', models.CharField(max_length=250)),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('officeorderFile', models.FileField(upload_to='lecture')),
            ],
        ),
    ]
