# Generated by Django 4.0.4 on 2022-05-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0009_upcominglectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='lastUpdated',
            field=models.DateField(auto_now=True),
        ),
    ]
