# Generated by Django 4.0.4 on 2022-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spav', '0012_remove_goiinitiative_logoimg_goiinitiative_goilogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goiinitiative',
            name='initTitle',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
